rango/urls.py
from django.conf.urls import url, patterns
import views

urlpatterns = patterns('',
		url(r'^$', views.index, name='index'),
		url(r'^add_category/$', views.add_category, name='add_category'),
		url(r'^category/(?P<category_enc_name>\w+)/$', views.category, name='category'),
		url(r'^add_page/(?P<category_enc_name>\w+)/$', views.add_page, name='add_page'),
		url(r'^register/$', views.register, name='register'),
		url(r'^login/$', views.user_login, name='user_login'),
		url(r'^logout/$', views.user_logout, name='user_logout'),
		url(r'^search/$', views.search, name='search'),
		url(r'^goto/$', views.goto_page_url, name='goto_page_url'),
		url(r'^users/$', views.view_all_users, name='view_all_users'),
		url(r'^user/(?P<username>\w+)/$', views.view_user, name='view_user'),
		url(r'^edit_profile/$', views.edit_profile, name='edit_profile'),
		url(r'^change_password/$', views.change_password, name='change_password'),
		url(r'^like_category/$', views.like_category, name='like_category'),
	)

tango_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tango_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^rango/', include('rango.urls',namespace="rango")),
)

import settings

if settings.DEBUG:
	urlpatterns+= patterns(
		'django.views.static',
		(r'media/(?P<path>.*)','serve',{'document_root':settings.MEDIA_ROOT})
	)

rango/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
	name = models.CharField(max_length=128, unique=True)
	views = models.IntegerField(default=0)
	likes = models.IntegerField(default=0)
	
	def __unicode__(self):
		return self.name
	
	class Meta:
		verbose_name_plural = "Categories"

class Page(models.Model):
	category = models.ForeignKey(Category)
	title = models.CharField(max_length=64)
	views = models.IntegerField(default=0)
	url = models.URLField()
	
	def __unicode__(self):
		return self.title

class UserProfile(models.Model):
	user = models.OneToOneField(User)
	website = models.URLField(blank=True)
	picture = models.ImageField(blank=True, upload_to='profile_images')
	
	def __unicode__(self):
		return self.user.username

rango/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from models import Category, Page, UserProfile
from form_models import CategoryForm, PageForm, UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.core.urlresolvers import reverse

def index(request):
	context = RequestContext(request)
	category_list = Category.objects.all()
	for cat in category_list:
		cat.enc_name = cat.name.replace(' ','_')
	context_dict = {'categories': category_list}
	return render_to_response('rango/index.html', context_dict, context)

def to_be_made(request):
	context = RequestContext(request)
	context_dict = {'base_body': "This page is yet to be implemented"}
	return render_to_response("rango/base.html", context_dict, context)

def category(request, category_enc_name):
	context = RequestContext(request)
	category_name = category_enc_name.replace('_',' ')
	context_dict = {"category_enc_name":category_enc_name}
	
	try:
		cat = Category.objects.get(name=category_name)
		cat.views+=1
		cat.save()
		pages = Page.objects.filter(category=cat).order_by('-views')
		context_dict['pages']=pages
		context_dict['category']=cat
	except Category.DoesNotExist:
		context_dict['base_title'] = "Rango - invalid category"
		context_dict['base_body'] = category_name + " is an invalid category"
		return render_to_response("rango/base.html", context_dict, context)
	
	return render_to_response("rango/category.html",context_dict,context)

def add_category(request):

	context = RequestContext(request)
	context_dict  = {}
	
	if request.user.is_authenticated():
		if request.method == "POST":
			form = CategoryForm(request.POST)
			if form.is_valid():
				newcat = form.save(commit=False)
				if len(Category.objects.filter(name=newcat.name))==0:
					newcat.save()
					context_dict["add_success"] = "Category "+newcat.name+" added successfully"
				else:
					context_dict["exists_error"] = "Category already exists"
					print("Category already exists")
		else:
			form = CategoryForm()
	
		context_dict['form']=form
		return render_to_response("rango/add_category.html", context_dict, context)

	else:
		context_dict['base_title'] = "Rango - not logged in"
		context_dict['base_body'] = "You can't add categories because you are not logged in"
		return render_to_response("rango/base.html", context_dict, context)
	
def add_page(request, category_enc_name):
	context = RequestContext(request)
	category_name = category_enc_name.replace('_',' ')
	context_dict = {'category_name':category_name, 'category_enc_name':category_enc_name}
	
	try:
		cat = Category.objects.get(name=category_name)
		if request.user.is_authenticated():
			if request.method=="POST":
				form = PageForm(request.POST)
				if form.is_valid():
					page = form.save(commit=False)
					page.category=cat
					page.save()
					context_dict["add_success"]="The page "+page.title+" was successfully added"
			else:
				form = PageForm()
			context_dict['form']=form
		else:
			context_dict['base_title'] = "Rango - not logged in"
			context_dict['base_body'] = "You can't add pages because you are not logged in"
			return render_to_response("rango/base.html", context_dict, context)
	except Category.DoesNotExist:
		context_dict['base_title'] = "Rango - invalid category"
		context_dict['base_body'] = category_name + " is an invalid category"
		return render_to_response("rango/base.html", context_dict, context)
	
	return render_to_response("rango/add_page.html", context_dict, context)
	
def register(request):
	context = RequestContext(request)
	context_dict = {}
#	register_success = True
	
	if request.method=="POST":
		uform = UserForm(request.POST)
		upform = UserProfileForm(request.POST)
		if uform.is_valid() and upform.is_valid():
			user = uform.save(commit=False)
			user.set_password(user.password)
			if user.email=="":
				context_dict["reg_error"]="Email address is required"
			elif User.objects.filter(email=user.email).count() > 0:
				context_dict["reg_error"]="This email address is already in use"
			else:
				user.save()
				uprofile = upform.save(commit = False)
				uprofile.user = user
				if 'picture' in request.FILES:
					uprofile.picture = request.FILES['picture']
				uprofile.save()
				context_dict["reg_success"]="Registration successful"
	else:
		uform = UserForm()
		upform = UserProfileForm()
	context_dict['uform'] = uform
	context_dict['upform'] = upform
	return render_to_response("rango/register.html", context_dict, context)

def user_login(request):
	context = RequestContext(request)
	context_dict = {}
	if request.method=="POST":
		username = request.POST["username"]
		password = request.POST["password"]
		
		#if username is invalid, treat it as email and try to get real username
		if User.objects.filter(username=username).count()==0:
			emails = User.objects.filter(email=username)
			if emails.count()==1:
				username = emails[0].username
		user = authenticate(username=username,password=password)
		
		if user:
			if user.is_active:
				login(request, user)
				return HttpResponseRedirect(reverse('rango:index'))
			else:
				context_dict["login_error"]="Your account has been disabled."
		else:
			context_dict["login_error"]="Failed to authenticate. Check username and password."
	return render_to_response("rango/login.html", context_dict, context)

def user_logout(request):
	if request.user.is_authenticated():
		logout(request)
		return HttpResponseRedirect(reverse('rango:index'))
	else:
		context = RequestContext(request)
		context_dict={
			"base_body":'You are already logged out.',
		}
		return render_to_response("rango/base.html", context_dict, context)

from bing_search import run_query

def search(request):
	context = RequestContext(request)
	context_dict = {}
	
	if request.method=="POST":
		query = request.POST["query"].strip()
		if query:
			result_list = run_query(query)
			context_dict["result_list"] = result_list
	
	return render_to_response("rango/search.html", context_dict, context)

def goto_page_url(request):
	context = RequestContext(request)
	context_dict = {}
	
	url=reverse('rango:index')
	try:
		if request.method=="GET" and ('page_id' in request.GET):
			page_id = request.GET["page_id"]
			page = Page.objects.get(id=page_id)
			page.views+=1
			page.save()
			url = page.url
			
	except Page.DoesNotExist:
		pass
			
	return HttpResponseRedirect(url)

def view_all_users(request):
	context = RequestContext(request)
	context_dict = {}
	users = User.objects.all()
	context_dict["users"] = users
	context_dict["no_of_users"] = len(users)
	return render_to_response("rango/view_all_users.html", context_dict, context)

def view_user(request, username):
	context = RequestContext(request)
	context_dict = {'username':username}
	
	try:
		cuser = User.objects.get(username=username)
		context_dict['cuser'] = cuser
		try:
			cuprofile = UserProfile.objects.get(user=cuser)
		except UserProfile.DoesNotExist:
			cuprofile = UserProfile(user=cuser)
			cuprofile.save()
		context_dict['cuprofile'] = cuprofile
		img_src = cuprofile.picture.name
		if img_src:
			img_src = (settings.MEDIA_URL+img_src)
			context_dict["img_src"] = img_src
	except User.DoesNotExist:
		pass
		
	return render_to_response("rango/view_user.html", context_dict, context)

def edit_profile(request):
	context_dict = {}

	if not request.user.is_authenticated():
		context_dict['base_title'] = "Rango - not logged in"
		context_dict['base_body'] = "You must log in to edit your profile."
		return render_to_response("rango/base.html", context_dict, context)

	user = User.objects.get(username=request.user.username)
	try:
		uprofile = UserProfile.objects.get(user=user)
	except UserProfile.DoesNotExist:
		uprofile = UserProfile(user=user)
		uprofile.save()
	
	if request.method=="POST":
		#set name
		user.first_name = request.POST["first_name"]
		user.last_name = request.POST["last_name"]
		user.save()
		request.user=user
		#set email
		email = request.POST["email"]
		if not email:
			context_dict["reg_error"]="Email cannot be blank"
		elif email!=user.email and User.objects.filter(email=email).count()>0:
			context_dict["reg_error"]="The email address "+email+" is already in use"
		else:
			user.email=email
			user.save()
			request.user=user
		
		upform = UserProfileForm(request.POST, instance=uprofile)
		if upform.is_valid():
			uprofile = upform.save(commit=False)
			if 'picture' in request.FILES:
				uprofile.picture = request.FILES['picture']
			uprofile.save()
		upform = UserProfileForm(request.POST, instance=uprofile)
	else:
		#get current user's secondary data
		upform = UserProfileForm(instance=uprofile)

	img_src = uprofile.picture.name
	if img_src:
		img_src = (settings.MEDIA_URL+img_src)
	context_dict["img_src"] = img_src
	
	context_dict['upform']=upform;
	return render_to_response("rango/edit_profile.html", context_dict, RequestContext(request))

def change_password(request):
	context = RequestContext(request)
	context_dict={}
	
	if not request.user.is_authenticated():
		context_dict['base_title'] = "Rango - not logged in"
		context_dict['base_body'] = "You must log in to change your password."
		return render_to_response("rango/base.html", context_dict, context)
	
	if request.method=="POST":
		pass1 = request.POST["pass1"]
		pass2 = request.POST["pass2"]
		if pass1!=pass2:
			context_dict["pass_error"] = "Passwords do not match"
		elif pass1=="":
			context_dict["pass_error"] = "Password can't be empty"
		else:
			request.user.set_password(pass1)
			request.user.save()
			context_dict["base_title"] = "Rango - password changed"
			context_dict["base_body"] = "Your password has been changed successfully."
			return render_to_response("rango/base.html", context_dict, context)

	return render_to_response("rango/change_password.html", context_dict, context)

templates/rango/add_category.html
{% extends "rango/base.html" %}

{% block title_block %}Rango - add category{% endblock %}
{% block h1_block %}Add a Category{% endblock %}

{% block body_block %}
<p style="color:green">{{add_success}}</p>
<p style="color:red">{{exists_error}}</p>
<form id="category_form" method="post" action="{% url 'rango:add_category' %}" class="span6">
	{% csrf_token %}
	{% for hidden in form.hidden_fields %}
		{{hidden}}
	{% endfor %}
		
	{% for field in form.visible_fields %}
		{{field.errors}}
		{{field.help_text}}
		{{field}}
		<br />
	{% endfor %}
	<button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

templates/rango/add_page.html
{% extends "rango/base.html" %}

{% block title_block %}Rango - Add page{% endblock %}
{% block h1_block %}Add a page to category: {{category_name}}{% endblock %}

{% block body_block %}
	{% if form %}
		<p style="color:green">{{add_success}}</p>
		<form id="page_form" method="post" action="{% url 'rango:add_page' category_enc_name %}">
			{% csrf_token %}
			{% for field in form.hidden_fields %}
				{{field}}
			{% endfor %}
			{% for field in form.visible_fields %}
				{{field.errors}}
				{{field.help_text}}
				{{field}}
				<br />
			{% endfor %}
			<button type="submit" class="btn btn-primary"/>Submit</button>
		</form>
		<p><a href="{% url 'rango:category' category_enc_name %}">Back to {{category_name}} pages</a></p>
	{% else %}
		<p style="color:red">{{category_name}} is an invalid category</p>
	{% endif %}
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>

{% load static %}
<html>
<head>
	<title>{% block title_block %}{{base_title |default:"Rango"}}{% endblock %}</title>
	<link rel="stylesheet" media="screen" href="{% static 'bootstrap2/css/bootstrap.min.css' %}" />
	<link rel="stylesheet" href="{% static 'bootstrap2/css/bootstrap-responsive.css' %}" />
	<link rel="stylesheet" href="{% static 'mybootstrap.css' %}" />
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<style>
	{% block style_block_def %}
		.helptext, .errorlist
		{font-size:12px;}
		.errorlist
		{color:red;}
	{% endblock %}
	</style>
	<style>{% block style_block %}{% endblock %}</style>
</head>
<body>

	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<div class="nav-collapse collapse">
					<ul class="nav pull-right">
						<li><a href="{% url 'rango:index' %}">Rango homepage</a></li>
						{% if user.is_authenticated %}
							<li><a href="{% url 'rango:view_user' user.username %}">Logged in as: {{user.username}}</a></li>
							<li><a href="{% url 'rango:user_logout' %}">Logout</a></li>
						{% else %}
							<li><a href="{% url 'rango:user_login' %}">Login</a></li>
							<li><a href="{% url 'rango:register' %}">Register</a></li>
						{% endif %}
					</ul>
				</div>
			</div>
		</div>
	</div>

	<!--sidebar and main body -->
	<div class="container-fluid">
		<div class="row-fluid">
			<div class="span3">
				<div class="well sidebar-nav">
					<ul>
						<li><a href="{% url 'rango:view_all_users' %}">View registered users</a></li>
					<ul>
				</div>
			</div>
			<div class="span9">
				<h1 style="text-align:center">{% block h1_block %}{% endblock %}</h1>
				<div class="hero-unit">
					<div class="container">
						{% block body_block %}{{base_body}}{% endblock %}
					</div>
				</div>
				{% block body2_block %}{{base_body2}}{% endblock %}
			</div>
		</div>
	</div>
	
	<script src="{% static 'bootstrap2/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/rango/category.html
{% extends "rango/base.html" %}

{% load static %}

{% block title_block %}Rango - {{category.name}}{% endblock %}
{% block h1_block %}{{category.name}}{% endblock %}
{% block style_block %}
.ekulm
{padding-right:20px;}
{% endblock %}

{% block body_block	%}
	<div class="container">
		<table class="span2">
			<!-- lm means leave margin -->
			<tr><td class="ekulm">Likes:</td><td id="like_count">{{category.likes}}</td></tr>
			<tr><td class="ekulm">Views:</td><td>{{category.views}}</td></tr>
		</table>
		{% if user.is_authenticated %}
			<button type="button" id="like" data-catid="{{category.id}}" class="btn btn-mini btn-primary">Like</button>
		{% endif %}
	</div>
	{% if pages %}
		<p>Pages in this category:</p>
		<ul>
			{% for p in pages %}
			<li><a href="{% url 'rango:goto_page_url' %}?page_id={{p.id}}">{{p.title}} ({{p.views}} views)</a></li>
			{% endfor %}
		</ul>
	{% else %}
		<p>There are no pages in this category</p>
	{% endif %}
	<p><a href="{% url 'rango:add_page' category_enc_name %}">Add pages to this category</a></p>
	{% if user.is_authenticated %}
		<script src="{% static 'js/rango-ajax.js' %}"></script>
	{% endif %}	
{% endblock %}

templates/rango/change_password.html
{% extends "rango/base.html" %}

{% block title_block %}Rango - change password{% endblock %}
{% block h1_block %}Change your password{% endblock %}

{% block body_block %}
<form id="cp_form" method="POST" action="{% url 'rango:change_password' %}" class="form-signin span4" >
	{% csrf_token %}
	<p style="color:red;">{{pass_error}}</p>
	<p>
		<span>Enter new password:</span>
		<input id="pfield1" type="password" name="pass1" value="" class="input-block-level" required="required" />
	</p>
	<p>
		<span>Retype new password:</span>
		<input id="pfield2" type="password" name="pass2" value="" class="input-block-level" required="required" />
	</p>
	<button type="submit" class="btn btn-primary">Submit</button> 
</form>
{% endblock %}

templates/rango/edit_profile.html
{% extends "rango/base.html" %}

{% block title_block %}Rango - edit profile{% endblock %}
{% block h1_block %}Edit your Profile{% endblock %}

{% block body_block %}
<p style="color:red;">{{reg_error}}</p>
<form id="user_form" method="POST" action="{% url 'rango:edit_profile' %}" enctype="multipart/form-data" class="form_signin">
	{% csrf_token %}
	{% if img_src %}
	<div><img src="{{img_src}}" alt="Profile picture" style="max-width:100px;max-height:100px;" /></div>
	{% endif %}
	<br />
	<table>
		<tr>
			<td>Email address:</td>
			<td><input type="email" name="email" value="{{user.email}}" required="required" /></td>
		</tr>
		<tr>
			<td>First Name:</td>
			<td><input type="text" name="first_name" value="{{user.first_name}}" /></td>
		</tr>
		<tr>
			<td>Last Name:</td>
			<td><input type="text" name="last_name" value="{{user.last_name}}" /></td>
		</tr>
		{{upform.as_table}}
	</table>
	<button type="submit" class="btn btn-primary">Save</button>
</form>
<p><a href="{% url 'rango:change_password' %}">Change Password</a></p>
{% endblock %}

templates/rango/index.html
{% extends "rango/base.html" %}
{% load static %}

{% block title_block %}Rango - Welcome{% endblock %}
{% block h1_block %}Welcome to Rango{% endblock %}

{% block style_block %}
.maincol
{
	display: inline-block;
	vertical-align:top;
	margin: 1em;
	text-align: left;
}
{% endblock %}

{% block body_block %}
<div style="text-align:left;">
<!--<div class="hero-unit">-->
	<img class="maincol" src="{% static 'sheriff.jpg' %}" alt="sheriff.jpg" />
	<div class="maincol">
		{% if categories %}
			<h3>Categories</h3>	
			<ul>
				{% for cat in categories %}
				<li><a href="{% url 'rango:category' cat.enc_name %}">{{cat.name}}</a></li>
				{% endfor %}
			</ul>
		{% else %}
			<p>There are no categories to display</p>
		{% endif %}
		<p><a href="{% url 'rango:add_category' %}">Add a category</a></p>
	</div>
</div>
{% endblock %}

templates/rango/login.html
{% extends "rango/base.html" %}
{% block title_block %}Rango - Login{% endblock %}
{% block h1_block %}Login to Rango{% endblock %}

{% block body_block %}
<p style="color:red">{{login_error}}</p>
<form id="login_form" method="POST" action="{% url 'rango:user_login' %}" class="form-signin span4">
	{% csrf_token %}
	Username:
	<input type="text" name="username" class="input-block-level" />
	<br />
	Password:
	<input type="password" name="password" class="input-block-level" />
	<br />
	<button type="submit" class="btn btn-primary">Sign in</button>
</form>
{% endblock %}

templates/rango/register.html
{% extends "rango/base.html" %}

{% block title_block %}Rango - Register{% endblock %}
{% block h1_block %}Register at Rango{% endblock %}

{% block body_block %}
	<p style="color:green">{{reg_success}}</p>
	<p style="color:red">{{reg_error}}</p>
	<form id="register_form" method="POST" action="{% url 'rango:register' %}" enctype="multipart/form-data" class="form-signin span8">
		{% csrf_token %}
		<table>
			{{uform.as_table}}
			{{upform.as_table}}
		</table>
		<button type="submit" class="btn btn-primary"/>Register</button>
	</form>
{% endblock %}

templates/rango/search.html
{% extends "rango/base.html" %}

{% block title_block %}Rango - Search{% endblock %}
{% block h1_block %}Search using Bing Search API{% endblock %}

{% block body_block %}
<form class="form-signin span8" id="search_form" method="post" action="{% url 'rango:search' %}">
	{% csrf_token %}
	<input type="text" id="query" name="query" class="input-block-level" />
	<button type="submit" class="btn btn-primary">Search</button>
</form>
{% endblock %}

{% block body2_block %}	
	{% if result_list %}
	<div style="clear:both;">
		<ol>
		{% for result in result_list %}
			<li>
				<strong><a href="{{result.link}}">{{result.title}}</a></strong><br />
				<em>{{result.summary}}</em>
			</li>
		{% endfor %}
		</ol>
	</div>
	{% endif %}
{% endblock %}

templates/rango/view_all_users.html
{% extends "rango/base.html" %}

{% block title_block %}Rango - users{% endblock %}
{% block h1_block %}List of all Rango users{% endblock %}
{% block style_block %}
td
{
	border: 1px solid black;
	padding: 2px 10px 2px 10px;
}
{% endblock %}

{% block body_block %}
	<p>Number of users: {{no_of_users}}</p>

	{% if no_of_users %}
		<table>
			<tr><td>username</td><td>Name</td></tr>
			{% for u in users %}
				<tr>
					<td><a href="{% url 'rango:view_user' u.username %}">{{u.username}}</a></td>
					<td>{{u.first_name}} {{u.last_name}}</td>
				</tr>
			{% endfor %}
		</table>
	{% endif %}
{% endblock %}

templates/rango/view_user.html
{% extends "rango/base.html" %}

{% block title_block %}Rango - profile{% endblock %}
{% block h1_block %}{{username}}'s Profile{% endblock %}

{% block body_block %}
	{% if cuser %}
		{% if cuser == user %}
			<p><a href="{% url 'rango:edit_profile' %}">Edit your profile</a></p>
			<p><a href="{% url 'rango:change_password' %}">Change your password</a></p>
		{% endif %}
		{% if img_src %}
			<img src="{{img_src}}" alt="Profile picture" style="max-width:200px;max-height:200px;" />
		{% endif %}
		<table>
			<tr>
				<td>Username:</td>
				<td>{{cuser.username}}</td>
			</tr>
			<tr>
				<td>Email:</td>
				<td>{{cuser.email}}</td>
			</tr>
			<tr>
				<td>Name:</td>
				<td>{{cuser.first_name}} {{cuser.last_name}}</td>
			</tr>
			<tr>
				<td>Website:</td>
				<td>{{cuprofile.website}}</td>
			</tr>
		</table>
	{% else %}
		<p>This user does not exist.</p>
	{% endif %}
{% endblock %}